### ISSUE TITLE
Failed to compile on 18.10, freadahead and rpl_fseeko need to be ported.

### ISSUE THREAD

**Issue by ghost** [c-sky/buildroot#12]
Hi,

I tried to buid bare buildroot by just setting the platform to csky and type to 610 and it failed:
```
  CC       printf-parse.o
  CC       vasnprintf.o
  CC       vasprintf.o
freadahead.c: In function 'freadahead':
freadahead.c:92:3: error: #error "Please port gnulib freadahead.c to your platform! Look at the definition of fflush, fread, ungetc on your system, then report this to bug-gnulib."
  #error "Please port gnulib freadahead.c to your platform! Look at the definition of fflush, fread, ungetc on your system, then report this to bug-gnulib."
   ^~~~~
make[4]: *** [Makefile:1915: freadahead.o] Error 1
make[4]: *** Waiting for unfinished jobs....
fseeko.c: In function 'rpl_fseeko':
fseeko.c:110:4: error: #error "Please port gnulib fseeko.c to your platform! Look at the code in fseeko.c, then report this to bug-gnulib."
   #error "Please port gnulib fseeko.c to your platform! Look at the code in fseeko.c, then report this to bug-gnulib."
    ^~~~~

```
I'm not sure what's causing this and how I can resolve it.

Can you help?

Thanks!
Edit:
I'm using the latest release, 1.0.4.

**Comment by guoren83** [comment]
We use buildroot as our CI SDK base, and all is tested on ubuntu 16.04
I don't know what's the package is. you can find out the error package and make it alone.

For buildroot:
make <package>-rebuild

**Comment by micwoj92** [comment]
@guoren83 ubuntu 16.04 is now EOL (unless you are using ESM), is there possibility to move to never ubuntu base for test machines?
